name: shik-test-job
volumes:
  site-db:

services:
  nginx:
    image: nginx:alpine
    ports:
      - 8081:80
    volumes:
      - ./site:/web-app:ro
      - ./site.conf:/etc/nginx/conf.d/default.conf:ro
    working_dir: /web-app
    depends_on:
      - php

  php:
    # container_name: site-php
    build:
      context: .
      dockerfile: php-docker.file
    volumes:
      - ./site:/web-app
    working_dir: /web-app
    user: 1000:1000
    depends_on:
      - db

  db:
    image: postgres:alpine
    volumes:
      - site-db:/var/lib/postgresql/data
      - ./dumps:/dumps
    working_dir: /dumps
    environment:
      POSTGRES_PASSWORD: shik
      POSTGRES_USER: shik
      POSTGRES_DB: shik



